language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm run test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
notifications:
  slack:
    on_success: always
env:
  - REACT_APP_TAB_TITLE="496 Project - Prod"
  - REACT_APP_PATH_BASE=http://gtest.dev.wwbtc.com
  - REACT_APP_JSON_EXTENSION=/json/rec